import React from 'react';
import photo1 from '../../assets/images/news1.webp'
import photo2 from '../../assets/images/news2.webp'
import photo3 from '../../assets/images/news3.webp'
import photo4 from '../../assets/images/news4.webp'

const newsData = [
  {
    "_id": "1",
    "photo": photo1,
    "title_uz": "Bug'doy",
    "title_ru": "Пшеница",
    "title_en":"Wheat",
    "title_ar":"گندم",
    "body_uz":"O'zbekistonda eng ko'p un tayyorlanadigan don bug'doy hisoblanadi. Har xil xususiyatlarga ega bo'lgan sharob ishlab chiqaradigan uzum navlarini va sharob ishlab chiqarish uchun uzumni aralashtirish tamoyilini hammamiz yaxshi bilamiz. Xuddi shunday, tegirmonchilar yuqori malakaga ega bo'lib, har bir mijoz talab qiladigan va yakuniy maqsadga eng mos keladigan un ishlab chiqarish uchun turli xil bug'doy navlarini baholash va aralashtirish uchun o'z bilim va mahoratidan foydalanadilar. Burger bulochkasida ishlatiladigan un pitssa uchun ishlatiladigan undan farq qiladi va baliq barmog'i yoki pechene uchun qo'llaniladigan undan farq qiladi. Oʻzbekistonda yetishtiriladigan bugʻdoy navlari davlat tomonidan tasdiqlangan sinov tizimi orqali tasdiqlanishi va Milliy roʻyxatga kiritilishi kerak. Un tegirmonchilari yangi navlarni non tayyorlash sifati va boshqa yakuniy foydalanish xususiyatlarini baholash uchun selektsionerlar bilan ishlaydi.",
    "body_ru":"Пшеница — это зерно, из которого производится большая часть муки в Узбекистане. Мы все знакомы с принципом производства вина из разных сортов винограда с разными характеристиками, а также с тем, как виноград смешивается для производства вина. Аналогичным образом, мукомолы имеют высокую квалификацию и используют свои знания и навыки для оценки и смешивания разных сортов пшеницы для производства муки в точном соответствии со спецификациями, требуемыми каждым клиентом, и которые лучше всего подходят для конечной цели. Мука, ​​используемая в булочке для бургера, отличается от муки, используемой для пиццы, и снова отличается от муки, используемой для покрытия крошек рыбных палочек или для печенья. Сорта пшеницы, выращиваемые в Узбекистане, должны быть одобрены через поддерживаемую правительством систему испытаний и включены в Национальный список. Мукомолы работают с селекционерами для оценки новых сортов на предмет их хлебопекарных качеств и других характеристик конечного использования.",
    "body_en":"Wheat is the grain from which most flour in the Uzbekistan is made. We are all familiar with the principle of grape varieties producing wine with different characteristics, and with grapes being blended to produce wines. Similarly, millers are highly trained and use their knowledge and skill to assess and blend different wheat varieties to produce flour to the exact specification required by each customer and which best suits the end purpose. Flour used in a burger bun is different to the flour used for pizzas, and different again to flour used in the crumb coating of a fishfingers or for biscuits. Wheat varieties grown in the Uzbekistan must be approved through a government backed testing system and included on the National List. Flour millers work with plant breeders to assess new varieties for their bread making quality and other end use characteristics. ",
    "body_ar":"گندم غله ای است که بیشتر آرد در ازبکستان از آن تهیه می شود. همه ما با اصل انواع انگور که شراب تولید می کنند با ویژگی های مختلف و با ترکیب انگور برای تولید شراب آشنا هستیم. به طور مشابه، آسیابان ها بسیار آموزش دیده اند و از دانش و مهارت خود برای ارزیابی و ترکیب انواع مختلف گندم برای تولید آرد با مشخصات دقیق مورد نیاز هر مشتری استفاده می کنند که به بهترین وجه با هدف نهایی مطابقت دارد. آردی که در نان برگر استفاده می شود با آردی که برای پیتزا استفاده می شود متفاوت است و دوباره با آردی که در روکش پودر ماهی یا بیسکویت استفاده می شود متفاوت است. گونه های گندمی که در ازبکستان رشد می کنند باید از طریق یک سیستم آزمایشی تحت حمایت دولت تایید شده و در فهرست ملی گنجانده شوند. آسیاب های آرد با پرورش دهندگان گیاهان کار می کنند تا گونه های جدید را از نظر کیفیت ساخت نان و سایر ویژگی های استفاده نهایی ارزیابی کنند.",
  
    
},
  {
    "_id": "2",
    "photo": photo2,
   "title_uz": "Tegirmonni qabul qilishda bug'doy sinovi",
    "title_ru": "Тестирование пшеницы на входе в мельницу",
    "title_en":"Wheat testing at mill intake",
    "title_ar":"آزمایش گندم در مصرف آسیاب",
    "body_uz":"Protein miqdori va sifati, o'ziga xos og'irligi, HFN (Hagberg Falling Number), SKCS raqami (Yagona yadro xarakteristikasi tizimi) va namlik miqdori yakuniy mahsulotning funksionalligiga ta'sir qiladi. Shu sababli, tegirmonchi uchun tegirmonda olinadigan bug'doyning xususiyatlarini tushunish juda muhim, shunda mijoz mo'ljallangan maqsadga muvofiq unni olishini ta'minlash uchun to'g'ri g'isht tayyorlanishi mumkin. “Uzbekistan Flour Millers” tegirmonini qabul qilish laboratoriyasi sxemasi un tegirmonlarida bug‘doyni sinovdan o‘tkazishning umumiy standartlarini o‘rnatish va saqlashga yordam beradi. Bu tegirmonchilardan o'z laboratoriyalarida belgilangan tartib-qoidalarga rioya qilishni, havola qilingan sinov usullarini qo'llashni va oylik sinovlar asosida Campden BRI tomonidan mustaqil ravishda baholanadigan malaka standartiga erishishni talab qiladi.",
    "body_ru":"Количество и качество белка, удельный вес, HFN (число падения Хагберга), число SKCS (система характеристики одного зерна) и содержание влаги — все это влияет на функциональность конечного продукта. Поэтому для мельника важно понимать характеристики пшеницы, принимаемой на мельнице, чтобы можно было сделать правильный помол, чтобы гарантировать, что клиент получит муку, пригодную для предполагаемой цели. Схема приемной лаборатории мельницы мукомольных предприятий Узбекистана помогает устанавливать и поддерживать общие стандарты испытаний пшеницы на мукомольных предприятиях. Она требует от мельников следовать установленным процедурам в своих лабораториях, использовать справочные методы испытаний и достигать стандарта квалификации, независимо оцениваемого Campden BRI на основе ежемесячных испытаний.",
    "body_en":"The amount and quality of the protein, the specific weight, the HFN (Hagberg Falling Number), the SKCS number (Single Kernel Characterisation System) and the moisture content all have impacts on the functionality of the end product. Therefore, it is important for the miller understand the characteristics of wheat taken in at the mill so that the correct grist can be made to ensure the customer receives flour which is fit for the purpose intended. The Uzbekistan Flour Millers mill intake laboratory scheme helps to establish and maintain common standards of wheat testing at flour mills. It requires millers to follow established procedures in their laboratories, use referenced testing methods and to reach a standard of proficiency, independently assessed by Campden BRI on the basis of monthly tests.",
    "body_ar":"مقدار و کیفیت پروتئین، وزن مخصوص، HFN (تعداد سقوطی هاگبرگ)، عدد SKCS (سیستم مشخصه هسته واحد) و میزان رطوبت، همگی بر عملکرد محصول نهایی تاثیر دارند. بنابراین، برای آسیابان مهم است که ویژگی‌های گندمی را که در آسیاب گرفته می‌شود، درک کند تا بتوان آسیاب درست کرد تا اطمینان حاصل شود که مشتری آرد متناسب با هدف مورد نظر را دریافت می‌کند. طرح آزمایشگاهی مصرف آسیاب آرد ازبکستان به ایجاد و حفظ استانداردهای مشترک آزمایش گندم در کارخانه های آرد کمک می کند. از آسیاب‌ها می‌خواهد که از روش‌های تعیین‌شده در آزمایشگاه‌های خود پیروی کنند، از روش‌های تست مرجع استفاده کنند و به استانداردی از مهارت برسند، که به طور مستقل توسط Campden BRI بر اساس آزمایش‌های ماهانه ارزیابی می‌شود."
},
  {
    "_id": "3",
    "photo": photo3,
"title_uz": "Frezeleme jarayoni",
    "title_ru": "Процесс фрезерования",
    "title_en":"The milling process",
    "title_ar":"فرآیند آسیاب",
    "body_uz":"Unni maydalash jarayoni bug'doyni ikkita katta tosh g'ildirak orasida maydalashdan kelib chiqqan (garchi bu jarayon hali ham bir nechta tegirmonlarda sodir bo'lsa ham). Rolikli tegirmonda amaliyot bug'doy urug'ining uchta komponentini - oq endospermni, tashqi kepak qatlamlarini va bug'doy urug'ini ajratishga qaratilgan. Ularning har biri turli xil materiallardan iborat bo'lib, alohida ajratilganda va maydalanganda, tegirmonchi nozikroq va shuning uchun bugungi kundagi foydalanish uchun ko'proq mos keladigan unlarni ishlab chiqarishi mumkin. Bug'doy tuzilishi haqida batafsil ma'lumot olish uchun bu yerni bosing. Quyidagi videoda bug'doyni unga aylantirish uchun zamonaviy un tegirmonida ishlatiladigan frezalash mashinalarining sxemasi va keng assortimenti ko'rsatilgan. Video mashinani ishlab chiqaruvchi Buhlerning ruxsati bilan ko'rsatiladi",
    "body_ru":"Процесс помола муки произошел от помола пшеницы между двумя большими каменными колесами (хотя этот процесс все еще происходит на некоторых мельницах). В вальцовой мельнице практика сосредоточена вокруг разделения трех компонентов семени пшеницы — белого эндосперма, внешних отрубевых слоев и зародыша пшеницы. Каждый из них состоит из разных материалов, и при разделении и помоле по отдельности мельник может производить муку, которая более мелкая и, следовательно, лучше подходит для сегодняшнего использования. Для получения более подробной информации о структуре пшеницы нажмите здесь. Видео ниже показывает схему и широкий спектр мукомольного оборудования, которое использовалось на современной мукомольной мельнице для переработки пшеницы в муку. Видео показано с любезного разрешения компании Buhler, которая производит оборудование",
    "body_en":"The flour milling process has evolved from wheat being ground between two large stone wheels (although this process does still occur in a few mills). In a roller mill the practice centres around separating the three components of a wheat seed – the white endosperm, the outer bran layers, and the wheat germ. These are each made up of different materials and, when separated and milled in isolation, the miller can produce flours that are finer and therefore better suited for today’s uses. For more detailed information on wheat structure click here. The video below shows the layout and vast range of milling machinery that it used in a modern flour mill to convert wheat into flour. The video is shown with the kind permission of Buhler who make the machinery",
    "body_ar":"فرآیند آسیاب آرد از آسیاب شدن گندم بین دو چرخ سنگی بزرگ تکامل یافته است (اگرچه این فرآیند هنوز در چند آسیاب انجام می شود). در آسیاب غلتکی، تمرین حول جداسازی سه جزء دانه گندم – اندوسپرم سفید، لایه های بیرونی سبوس، و جوانه گندم متمرکز است. اینها هر کدام از مواد مختلفی تشکیل شده‌اند و در صورت جداسازی و آسیاب کردن جداگانه، آسیاب می‌تواند آردهایی تولید کند که ریزتر هستند و بنابراین برای مصارف امروزی مناسب‌تر هستند. برای اطلاعات بیشتر در مورد ساختار گندم اینجا را کلیک کنید. ویدئوی زیر طرح و طیف وسیعی از ماشین آلات آسیاب را نشان می دهد که در یک آسیاب آرد مدرن برای تبدیل گندم به آرد استفاده می شود. این ویدئو با اجازه بوهلر که ماشین آلات را می سازد نمایش داده می شود",
},
  {
    "_id": "4",
    "photo": photo4,
"title_uz": "Un",
    "title_ru": "Мука",
    "title_en":"Flour",
    "title_ar":"آرد",
    "body_uz":"Un bug'doydan tayyorlangan tabiiy mahsulotdir. Tegirmonlash jarayoni bug'doy urug'ining uchta tarkibiy qismini ajratish va ularni rulonlar orasiga maydalashni o'z ichiga oladi. O‘zbekistonda biz iste’mol qiladigan unning qariyb 85 foizi o‘zimizda yetishtirilgan bug‘doydan olinadi. O'zbekistonda va butun dunyoda un ko'p qirrali va qimmatli ingredient hisoblanadi. U keng assortimentdagi mahsulotlarda qo'llaniladi - non, kek va pechenedan kolbasa, soslar va hatto qandolat mahsulotlarigacha. Hisob-kitoblarga ko'ra, O'zbekistondagi barcha oziq-ovqat mahsulotlarining qariyb uchdan bir qismi unni o'z ichiga oladi - bularning barchasini a'zolarimizdan biri tegirmon qilgan bo'lar edi.",
    "body_ru":"Мука — это натуральный продукт, изготавливаемый из пшеницы. Процесс помола включает в себя разделение трех составных частей пшеничного семени и помол их между вальцами. В Узбекистане около 85% потребляемой нами муки измельчается из выращенной в стране пшеницы. В Узбекистане и во всем мире мука — это универсальный и ценный ингредиент. Она используется в широком ассортименте продуктов — от хлеба, тортов и печенья до колбас, соусов и даже кондитерских изделий. По оценкам, около трети всех продуктовых товаров в Узбекистане содержат муку — и все это должно было быть помолото одним из наших членов.",
    "body_en":"Flour is a natural product made from wheat. The milling process involves separating the three component parts of the wheat seed and milling them between rollers. In the Uzbekistan, about 85% of the flour we consume is milled from homegrown wheat. In the Uzbekistan and around the world flour is a versatile and valuable ingredient. It is used in a wide-range of products – from bread, cakes and biscuits to sausages, sauces and even confectionary. It is estimated that around one third of all grocery items in the Uzbekistan contain flour – all of which would have been milled by one of our members. ",
    "body_ar":"آرد یک محصول طبیعی است که از گندم تهیه می شود. فرآیند آسیاب شامل جداسازی سه قسمت از دانه گندم و آسیاب کردن آنها بین غلتک ها است. در ازبکستان، حدود 85 درصد آرد مصرفی ما از گندم بومی آسیاب می شود. در ازبکستان و در سراسر جهان آرد یک ماده همه کاره و ارزشمند است. در طیف گسترده ای از محصولات - از نان، کیک و بیسکویت گرفته تا سوسیس، سس و حتی قنادی استفاده می شود. تخمین زده می شود که حدود یک سوم اقلام مواد غذایی در ازبکستان حاوی آرد است - که همه آنها توسط یکی از اعضای ما آسیاب شده است.",
  
  
  
}
];

// To'g'ri eksport qilish:
export default newsData;
